"""Test04

Revision ID: 04f9c4558e66
Revises: e0135d6e4745
Create Date: 2023-03-20 22:45:00.177828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f9c4558e66'
down_revision = 'e0135d6e4745'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('pub_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('pub_year', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('num_citations', sa.Integer(), nullable=True),
    sa.Column('eprint_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pub_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper')
    # ### end Alembic commands ###
