"""Test01

Revision ID: 38412be07f8a
Revises: 740bdac1df05
Create Date: 2023-03-20 22:28:07.586102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38412be07f8a'
down_revision = '740bdac1df05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
