"""added column pdfpath

Revision ID: 51419ff42aeb
Revises: c050c1881fd1
Create Date: 2023-03-21 00:45:31.906188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51419ff42aeb'
down_revision = 'c050c1881fd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('pdf_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'pdf_path')
    # ### end Alembic commands ###
