"""added column scrape source

Revision ID: a9ec4a80c7f8
Revises: 51419ff42aeb
Create Date: 2023-03-21 00:49:12.338006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ec4a80c7f8'
down_revision = '51419ff42aeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('scrape_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'scrape_source')
    # ### end Alembic commands ###
