"""publisher name update

Revision ID: bebb800f7d8f
Revises: 04f9c4558e66
Create Date: 2023-03-20 22:59:04.380339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebb800f7d8f'
down_revision = '04f9c4558e66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('publisher_name', sa.String(), nullable=True))
    op.drop_column('paper', 'venue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('venue', sa.VARCHAR(), nullable=True))
    op.drop_column('paper', 'publisher_name')
    # ### end Alembic commands ###
