"""init

Revision ID: c050c1881fd1
Revises: 
Create Date: 2023-03-20 23:44:42.928471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c050c1881fd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('pub_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pub_year', sa.String(), nullable=True),
    sa.Column('publisher_name', sa.String(), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('num_citations', sa.Integer(), nullable=True),
    sa.Column('eprint_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper')
    # ### end Alembic commands ###
